### ISSUE TITLE
Allow specific version of puppet to be installed when using puppet-collections

### ISSUE THREAD

**Issue by jrwesolo** [neillturner/kitchen-puppet#106]
According to the code, it doesn't seem that if I use `require_puppet_collections: true` I can choose what version I want to install. It will always install the latest. I'd love this support.

**Comment by neillturner** [comment]
current i just support install from a repo and allow you to specify the url of the repo. I believe that you 
i can see that there are multiple versions at: 
  https://downloads.puppetlabs.com/puppet/
but i have never supported install from here in puppet v3.

**Comment by jrwesolo** [comment]
Sorry if I wasn't clear. When I choose `require_puppet_collections: true` it uses the PC1 repo. For example, with CentOS 6, it uses http://yum.puppetlabs.com/el/6/PC1/x86_64/. The code [here](https://github.com/neillturner/kitchen-puppet/blob/b3111765167eae5a2e6a4c40a624e80514353637/lib/kitchen/provisioner/puppet_apply.rb#L249) installs the package `puppet`.

This actually installs the package `puppet-agent` at the latest version. I propose we instead install puppet-agent (that is the naming scheme that is used now from these PC repos) at a specific version. Something like:
`#{sudo_env('yum')} -y install puppet-agent#{puppet_version}`

That would make it similar to how you allow specific puppet versions installed when < 4.

**Comment by neillturner** [comment]
another possibility is there are some good puppet install scripts at: 
https://github.com/petems/puppet-install-shell
that i could easily link to to allow a version to be specified.

**Comment by jrwesolo** [comment]
I'll submit a pull request so it's more obvious what I'm asking.

**Comment by jrwesolo** [comment]
I went ahead and submitted https://github.com/neillturner/kitchen-puppet/pull/107. In response to your last statement, I could see all this logic being replaced with one of those scripts that you mentioned. That would be nice.
