### ISSUE TITLE
Ignore fixtures path

### ISSUE THREAD

**Issue by petems** [neillturner/kitchen-puppet#108]
Ended up with this amazing stack trace:
<img width="1432" alt="screenshot 2016-02-25 23 47 25" src="https://cloud.githubusercontent.com/assets/1064715/13338569/28fb4f72-dc1a-11e5-9298-31e5ed79574d.png">

We should probably ignore the spec/fixtures/ directory, as it recursively refers to itself...

**Comment by neillturner** [comment]
ok will do a new option to allow you to ignore it.

**Comment by neillturner** [comment]
closed. in version 1.40.0

**Comment by petems** [comment]
Awesome 👍

**Comment by neillturner** [comment]
Actually i also added an omnibus_puppet install option that points to your puppet-install-shell  scripts. -) 
Didn't think puppetlabs folks would like my plugin as they have beaker. -)

**Comment by petems** [comment]
hah, we welcome all tools. But I'm glad my scripts work 😄
