### ISSUE TITLE
Support for Puppet ENC

### ISSUE THREAD

**Issue by elconas** [neillturner/kitchen-puppet#116]
If using shell script ENC, we would like to specify the ENC script for puppet for the puppet apply provisioner: 

provisioner: 
  puppet_enc: enc/puppet_enc.sh

This should copy enc/puppet_enc.sh to /tmp/kitchen/enc and add the following option to puppet apply: 

  --node_terminus=exec --external_nodes=/tmp/kitchen/enc

The file /tmp/kitchen/files/enc should be chmod "755" after copying.

**Comment by neillturner** [comment]
that should be pretty straight forward. i should be able to get that in the next version.

**Comment by elconas** [comment]
Great, I tried, but my "ruby" is too bad :)

**Comment by neillturner** [comment]
shipped in version 1.39.0

**Comment by elconas** [comment]
Fixed ENC Implementation https://github.com/neillturner/kitchen-puppet/pull/126
