### ISSUE TITLE
Headsup: Doesn't work with Test Kitchen 1.7.0

### ISSUE THREAD

**Issue by peterabbott** [neillturner/kitchen-puppet#117]
I got caught out today because I was updating some gem depdencies and during the update I pulled in the new version of Test Kitchen. 

There is an issue with the script block that checks that Puppet and its dependencies are installed. When I run the script block it complains about it runs fine, it appears to be the way we execute a command. If I roll back to 1.6 for test kitchen everything runs fine. Still looking at exactly what has changed to see if I can fix it.

Ran against Vagrant and Docker to rule out the platform provider.

Just wanted to let other know incase the get caught out and waste a morning arguing with the keyboard as to why something just stopped working :)

**Comment by peterabbott** [comment]
The relevant bit is that the concatenated script that is executed includes some functions 

```
# Check whether a command exists - returns 0 if it does, 1 if it does not
exists() {
...
}
...
````

The error that comes back is 
```
'      bash: -c: line 34: syntax error near unexpected token `{
'      bash: -c: line 34: `exists() {
```

And line 34 correlates to the first function block in the full generated script. 

Off to the release notes for Test Kitchen to see what has changed....

**Comment by grubernaut** [comment]
Awesome, thanks for the heads up!

**Comment by neillturner** [comment]
it useful to run with -l debug on the command and then we see the traceback. usualy these issues are simple to fix once we ca see the cause of the issue. the changelog on kichen 1.7.0 doesn't suggest any reason.

**Comment by peterabbott** [comment]
That didn't give me any other clues other than the full script it was running. If I copy that on to the VM and run it goes through fine. At a guess maybe there is something with the variable interpolation??

The bit of script it complains about is coming from the download helpers block that is appended to the provision script for the puppet install check  (https://github.com/test-kitchen/test-kitchen/blob/master/support/download_helpers.sh) But that is probably a red herring and is likely something before that. 

I can post the full output tomorrow when I get a chance. to see if anybody else can see something obvious

**Comment by neillturner** [comment]
well i cannot tell if the bug is in test-kitchen itself or in the kitchen-puppet plugin. the download_helpers are part of test-kitchen itself. test-kitchen is responsible for uploading the files to the remote server before kitchen-puppet is called the install and converge

**Comment by neillturner** [comment]
I tested on test-kitchen 1.7.0 with Centos 7.0 on AWS and couldn't get the problem.

**Comment by peterabbott** [comment]
Just tested with test-kitchen 1.7.3 on Docker and Vagrant/VB and seems to work. Rolling back to 1.7.0 and I still get the same error as before.

I wonder if there was a transitive dependency that has since been updated that resolved the issue??

On another happy note, the latest beta of Docker for Mac now plays nicely with Test Kitchen, but that is a different topic :)

**Comment by neillturner** [comment]
I think we will call it test-kitchen problem if it works on test-kitchen 1.7.3. 
test-kitchen are in a bit of bother as they still have 45 outstanding pull requests and 123 open issues.
