### ISSUE TITLE
PR #77 now makes modules_path mandatory

### ISSUE THREAD

**Issue by cliles** [neillturner/kitchen-puppet#120]
PR #77 introduces breaking changes when not specifying modules_path

'''
Kitchen::ActionFailed: Failed to complete #converge action: [undefined method `include?' for nil:NilClass]
/u01/jenkins/.gem/ruby/2.0/gems/kitchen-puppet-1.40.0/lib/kitchen/provisioner/puppet_apply.rb:968:in `prepare_modules'
/u01/jenkins/.gem/ruby/2.0/gems/kitchen-puppet-1.40.0/lib/kitchen/provisioner/puppet_apply.rb:426:in `create_sandbox'
/u01/jenkins/.gem/ruby/2.0/gems/test-kitchen-1.7.3/lib/kitchen/provisioner/base.rb:63:in `call
'''

**Comment by neillturner** [comment]
thanks for letting me know about this regression. fixed in version 1.40.1. closing.

**Comment by cliles** [comment]
ty!
