### ISSUE TITLE
Gem Dependency busser-hieradata is missing?

### ISSUE THREAD

**Issue by chad-thompson** [neillturner/kitchen-puppet#125]
When running a kitchen-puppet test after defining `  hiera_data_path: hieradata` I am encountering an error in running serverspec tests:  the `kitchen verify` step wants to install a gem called `busser-hieradata`, which is failing:

```
Fetching: busser-0.7.1.gem (100%)
       Successfully installed busser-0.7.1
       2 gems installed
       Installing Busser plugins: busser-hieradata busser-serverspec
       /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/resolver/installer_set.rb:71:in `add_always_install': Unable to resolve dependency: user requested 'busser-hieradata (>= 0)' (Gem::UnsatisfiableDependencyError)
```

... and upon verification (both doing a local `gem install` as well as a sanity check on rubygems.org) - there does not appear to be a `busser-hieradata` gem.  Is this simply a mis-configuration?

I'm using testkitchen 1.9.0, kitchen-puppet version 1.41.1.

Thank you!

**Comment by neillturner** [comment]
This is actually not to do with the provisioner but the verifier which is part of test kitchen core. 
how busser works is that when it finds test/integration/default/serverspec it figures out it needs to install busser-serverspec so i suspect you have test/integration/default/hieradata and it is trying to install busser-hieradata
  http://stackoverflow.com/questions/29812546/testing-chef-roles-and-environments shows example from chef point of view
Personally i recommend bypassing busser completely and using my 
kitchen-verifier-serverspec as its much simplier and have more options.
