### ISSUE TITLE
Strange error when using puppet_environment

### ISSUE THREAD

**Issue by peterabbott** [neillturner/kitchen-puppet#137]
Still trying to work this out to try and fix,  but there seems to be an issue with 1.43 and 1.44 around the cleanup logic 

```
      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [no implicit conversion of String into Array] on node-centos-7
D      ----------------------
```

The line is /.rvm/gems/ruby-2.1.5/gems/kitchen-puppet-1.44.1/lib/kitchen/provisioner/puppet_apply.rb:475:in `init_command'
```

The code is this, so it looks like it is trying to append a string to an array 
```
todelete += [hiera_data_remote_path,
                     '/etc/hiera.yaml',
                     "#{puppet_dir}/hiera.yaml",
                     spec_files_remote_path.to_s,
                     "#{puppet_dir}/fileserver.conf"]
todelete += File.join(puppet_dir, config[:puppet_environment]) if config[:puppet_environment]
```

If I use 1.42 it passes, but newer versions fail. 

I can see that the difference is that in 42 it was treated as a string.

```
        cmd = "#{sudo('rm')} -rf #{dirs} #{hiera_data_remote_path} \
              /etc/hiera.yaml #{puppet_dir}/hiera.yaml \
              #{spec_files_remote_path} \
              #{puppet_dir}/fileserver.conf;"
        cmd += config[:puppet_environment] ? "#{sudo('rm')} -f #{File.join(puppet_dir, config[:puppet_environment])};" : ''
```

**Comment by peterabbott** [comment]
This fixes https://github.com/neillturner/kitchen-puppet/pull/138

**Comment by neillturner** [comment]
thanks for that. i need to improve the test suite to stop these regressions. but the plugins in now fairly fully functional so doesn't need lots of development now.
