### ISSUE TITLE
puppet provisioner does not work properly with --detailed-exit-codes

### ISSUE THREAD

**Issue by elconas** [neillturner/kitchen-puppet#147]
When specifying detailed-exit-codes, you must also use whitelist exist codes. However this is not properly implemented, as whitelist-exit-codes only accepts one value on linux puppet_kitchen: 

puppet-kitchen needs to capture detailed existcodes 0 (already converged) and 2 (no failure during apply)

**Comment by neillturner** [comment]
merge will release shortly
