### ISSUE TITLE
hiera-cli does not honor /etc/hiera or /etc/puppet/hiera.yaml on Ubuntu 16.04

### ISSUE THREAD

**Issue by stefanandres** [neillturner/kitchen-puppet#151]
Hi, when using the hiera cli it does not lookup items because of does not find the hiera.yaml

```
kitchen@cc3c3c0e4536:~$ sudo hiera -a classes
Failed to start Hiera: RuntimeError: Config file /etc/puppetlabs/code/hiera.yaml not found
```

**Comment by neillturner** [comment]
do you have a kitchen.yml file that you used to get problem

**Comment by neillturner** [comment]
tested this this is because the hiera.yaml file will be in /tmp/kitchen area try: 
  sudo hiera -a classes -c /tmp/kitchen/hiera.yaml
