### ISSUE TITLE
puppet_apt_collections_repo uses wrong repo

### ISSUE THREAD

**Issue by stefanandres** [neillturner/kitchen-puppet#154]
E.g. when using Ubuntu-14.04 it should use https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb, same for the other Debian/Ubuntu versions (see https://apt.puppetlabs.com/)

**Comment by neillturner** [comment]
Ok I  updated  the docs at https://github.com/neillturner/kitchen-puppet/blob/master/provisioner_options.md. 
should we make the default   puppetlabs-release-pc1-precise.deb  so it 
matches the default for the non-collections version of ubuntu. 

I could determine dynamically but that will make the install script more complex and create a 
maintenance requirement although feel free to write a pull request. -)  
 
You can find the Debian version on which your Ubuntu version is based in the file: /etc/debian_version

From 10.04 up to 17.04:

17.04  zesty      stretch / sid
16.10  yakkety    stretch / sid
16.04  xenial     stretch / sid
15.10  wily       jessie  / sid
15.04  vivid      jessie  / sid
14.10  utopic     jessie  / sid
14.04  trusty     jessie  / sid
13.10  saucy      wheezy  / sid
13.04  raring     wheezy  / sid
12.10  quantal    wheezy  / sid
12.04  precise    wheezy  / sid
11.10  oneiric    wheezy  / sid
11.04  natty      squeeze / sid
10.10  maverick   squeeze / sid
10.04  lucid      squeeze / sid
sid is the development distribution of Debian (sid - testing - stable)

**Comment by stefanandres** [comment]
yep, I see. Well, I've worked around it by using docker container which have puppet-4 preinstalled anyways (to save time for new test instances) ;)

**Comment by neillturner** [comment]
that's a good idea too -)
