### ISSUE TITLE
Problem with installing puppet

### ISSUE THREAD

**Issue by es1o** [neillturner/kitchen-puppet#158]
Hello I've a problem. I'm trying to install puppet4, I've enabled repo with puppet collections but kitchen-puppet tried install puppet-agent package, but in puppet collections packane name is 'puppet'.

Is it possible to change puppet package name?

**Comment by neillturner** [comment]
what parameters did you specify in kitchen.yml file 
and run with -l debug to see the log

**Comment by es1o** [comment]
It was my fault, you can close this issue.
