### ISSUE TITLE
no_proxy support?

### ISSUE THREAD

**Issue by cliles** [neillturner/kitchen-puppet#161]
It would be great if the provisioner had env_vars or no_proxy support.

**Comment by neillturner** [comment]
Well you could create a PR and use the env_vars and no_proxy code from my        https://github.com/neillturner/kitchen-ansible
I will try and do when i get time. busy on a contract at the moment.

**Comment by cliles** [comment]
Please see PR #162

**Comment by neillturner** [comment]
thanks
