### ISSUE TITLE
Support Directory Environments

### ISSUE THREAD

**Issue by elconas** [neillturner/kitchen-puppet#170]
Hello, 
puppet 4 supports directory environments (See https://docs.puppet.com/puppet/4.10/environments_creating.html#structure-of-an-environment environmentsdir), allowing for per environment hiera5 config files (see puppet 4.10 https://docs.puppet.com/puppet/4.10/hiera_layers.html). We use kitchen-puppet to provide a "master like" local test environments. All of our masters use directory environments and per env hiera. 

To test this, we have to "highjack" the files_path setting and patch the provider to allow specifying a "envronmentsdir" config option. Then this setting works:

```
---
provisioner:
  files_path: ./
puppet_environment: files
```

However this is ugly as we "loose" files_path and it is more or less really ugly.

It would be great if the provisioner would support directory environments, then copying everyting (including environments.conf) to the environmentspath with ```puppet_environment``` as folder name.

**Comment by elconas** [comment]
By the way, we use kitchen-puppet for the control repo and individual puppet modules.

**Comment by elconas** [comment]
Pseudo Code: 
```
environmentsdir = config param

if environmentsdir.to_s != ''
  fail if "environment.conf" is missing
  copy modules to $root_path/environments/modules
  copy manifests to $root_path/environments/manifests
  copy environment.conf to $root_path/environments/
  if exists(hiera.yaml)
    copy hiera.yaml to $root_path/environments/
  end
  add "--environmentpath $root_path/environments" to CLI Command
end
```

**Comment by elconas** [comment]
@neillturner Any release planned ?

**Comment by neillturner** [comment]
yes. i will just test it today and tomorrow
