### ISSUE TITLE
cp: cannot stat `/tmp/kitchen/hiera/*': No such file or directory

### ISSUE THREAD

**Issue by cohenaj194** [neillturner/kitchen-puppet#177]
So I followed the basic guide on this repo for using [kitchen-puppet for the first time](http://ehaselwanter.com/en/blog/2014/05/08/using-test-kitchen-with-puppet/) and ran into an issue I was having with the original repository I wanted to use this for.

Whenever I attempt to run `kitchen converge` I continue to get the error message:

```
cp: cannot stat `/tmp/kitchen/hiera/*': No such file or directory
```

The issue could be that I am running this though bundler (version 1.14.6) and I also set my puppet version to the same one as the guide `gem "puppet", "~> 4.10.4"` to get around librarian-puppet issues.  Here is the full output of my converge:

```
$ bundle exec kitchen converge
-----> Starting Kitchen (v1.16.0)
-----> Converging <default-nocm-ubuntu-1204>...
       Preparing files for transfer
       Preparing modules
       Resolving module dependencies with Librarian-Puppet 2.2.3...
       Preparing manifests
       Preparing files
       nothing to do for files
       Preparing hiera data
       Finished Preparing files for transfer
       Installing puppet, will try to determine platform os
       Install busser on nocm_ubuntu
       Transferring files to <default-nocm-ubuntu-1204>
       cp: cannot stat `/tmp/kitchen/hiera/*': No such file or directory
-----> Converging <default-centos-65>...
       Preparing files for transfer
       Preparing modules
       Resolving module dependencies with Librarian-Puppet 2.2.3...
       Preparing manifests
       Preparing files
       nothing to do for files
       Preparing hiera data
       Finished Preparing files for transfer
       Installing puppet from yum on centos
       Install busser on centos
       Transferring files to <default-centos-65>
       cp: cannot stat `/tmp/kitchen/hiera/*': No such file or directory
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 2 actions failed.
>>>>>>     Converge failed on instance <default-nocm-ubuntu-1204>.  Please see .kitchen/logs/default-nocm-ubuntu-1204.log for more details
>>>>>>     Converge failed on instance <default-centos-65>.  Please see .kitchen/logs/default-centos-65.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by neillturner** [comment]
this is a sample repo to get started at: 
  https://github.com/neillturner/puppet_vagrant_repo
suggest you compare your repo to that

**Comment by cohenaj194** [comment]
Ok so some changes had to be made but looking at the [puppet_vagrant_repo](https://github.com/neillturner/puppet_vagrant_repo) example I copied over the `modules_mycompany` directory and was able to create a `hieradata` directory that is filled with empty files.  

```
hieradata/
├── common.yaml
└── roles
    └── default.yaml
```

I also copied the `hiera.yaml file` over (although I did not change it and may still need to):

```
---
:backends:
  - yaml
:yaml:
  :datadir: /var/lib/hiera
:hierarchy:
  - "nodes/%{hostname}"
  - "%{::environment}/roles/%{role_name1}"
  - "%{::environment}/roles/%{role_name2}"
  - "%{::environment}/roles/%{role_name3}"
  - "%{::environment}/roles/%{role_name4}" 
  - "%{::environment}/common"  
  - "roles/%{role_name1}"
  - "roles/%{role_name2}"
  - "roles/%{role_name3}"
  - "roles/%{role_name4}"	
  - common
```

And made some changes to the basic Gemfile in the guide to get everything running:

```
source 'https://rubygems.org'

gem "test-kitchen"
gem "kitchen-puppet"
gem "kitchen-vagrant"
gem "puppet", "~> 4.10.4"
gem "librarian-puppet"
```

It will at this point successfully converge.  It may be a useful feature to have some scripts or gems that create this hiera file structure.

**Comment by neillturner** [comment]
you don't need my hiera.yaml you can have a n empty one. hiera is part of puppet these days. 
see https://docs.puppet.com/hiera/3.3/configuring.html

**Comment by cohenaj194** [comment]
Hmm I guess it was the missing `hieradata/` file structure that was causing the issue.
