### ISSUE TITLE
Disable site.pp as default config for manifest in puppet_apply

### ISSUE THREAD

**Issue by pesimon** [neillturner/kitchen-puppet#181]
Hi, 

I'd like to suggest to disable [defaulting](https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L96
) to `site.pp` if manifest config is not set. 

This prevents people to use multiple *.pp files in the manifests directroy that are being loaded from puppet. 
https://docs.puppet.com/puppet/5.0/dirs_manifest.html#directory-behavior-vs-single-file

As workaround you could set `manifest: ''` in `.kitchen.yml` to get the directory behavior in puppet apply.

**Comment by neillturner** [comment]
That's probably a good idea as it makes it like how terraform works. -) 
I suggest I change the docs:
1. manifest_path parameter default  to say 'mainfests' as that is what is does.
2.  manifest to  default to say  "Puppet parses every .pp file in the mantifest_path directory and it subdirectory subdirectories" . and in the comments add it can be set to 'site.pp' for example. 
or i could create a new parameter say Directory behavior and set it to true.

**Comment by neillturner** [comment]
implemented in version 3.1.0
