### ISSUE TITLE
No example of facter_file

### ISSUE THREAD

**Issue by cgetzen** [neillturner/kitchen-puppet#185]
Hello!
The Puppet Apply Provisioner Option "facter_file" seems ambiguous, and I don't think my project is using it the right way:

.kitchen.yml
```
...
provisioner:
  ...
  custom_pre_apply_command: |
    cat <<EOF >> /tmp/kitchen/facter/kitchen.rb
    require_relative 'default_facts'
    include RSpec::Support::DefaultFacts
    RSpec::Support::DefaultFacts::default_facts.each do |key, value|
      Facter.add(key) do
        setcode do
          value
        end
      end
    end
    EOF
  facter_file: shared_spec/support/default_facts.rb
  install_custom_facts: true
```

shared_spec/support/default_facts.rb
```
module RSpec
  module Support
    module DefaultFacts
      def default_facts
        {key1: 'value1', ... }
      end
    end
  end
end
```

Is it possible to add an example of the right way to use facter_file in provisioner_options.md? 

Is it possible to re-use the code in default_facts.rb?

**Comment by neillturner** [comment]
you can see an example facter file here: 
   https://github.com/neillturner/puppet_vagrant_repo/tree/master/facter
See also (try goggling puppet custom facts)
  https://docs.puppet.com/facter/3.8/custom_facts.html
  http://puppetlunch.com/puppet/custom-facts.html
you can specify facts in the .kitchen.yml 
as an array 
```yaml
custom_facts:
  list_of_ips:
    - 10.0.0.1
    - 192.168.10.10
```
or a hash: 
```yaml
custom_facts:
  role_name1: base
  role_name2:  iis
```
or string
```yaml
custom_facts: role_name1=base,role_name2=webserver
```

**Comment by cgetzen** [comment]
The notes on facter_file say
`facter_file: yaml file of custom facter_files to be provided to the puppet-apply command` 

but your [example facter file](https://github.com/neillturner/puppet_vagrant_repo/tree/master/facter) is ruby. Can it be either?

**Comment by neillturner** [comment]
fair enough. i've corrected the docs. i think they can be yaml as well.  certainly external facts can be yaml as per
 https://stackoverflow.com/questions/45825601/puppet-facter-how-to-set-custom-facts-from-yaml-file.   I would have to read up on the exact difference between external facts and custom facts.  Haven't written any puppet this year to be frank, Been working alot with HashiCorp products Terraform and Packer and AWS ofcourse.
