### ISSUE TITLE
Don't copy unneeded files when testing a Puppet module

### ISSUE THREAD

**Issue by stefanbethke** [neillturner/kitchen-puppet#193]
In our Puppet modules, we use kitchen-puppet to run serverspec tests. Our setup includes an examples directory with a site.pp, some Hiera config and data, and a Puppetfile. Under examples/modules, librarian-puppet will place all required modules as per the Puppetfile.

To include the module under test in this list, we've specified in Puppetfile:
```
mod 'mms/mms_puppet_jenkins',
  path: "../"
```

This leads kitchen-puppet to transfer the entire module into the Vagrant box, which takes a significant amount of time. Since some of our modules include quite a number of suites, running the integration tests mutiplies

We're hoping to be able to speed up the copying process by having kitchen-puppet only copy the relevant files of this module into the box. We're happy to configure a list of patterns for that (either include or exclude).

For one of our modules, the difference in size between everything and only the bits needed for Puppet are significant:
```
$ du -sh .
 31M	.
$ du -sh data functions hiera.yaml lib manifests metadata.json Puppetfile templates
212K	data
8.0K	functions
4.0K	hiera.yaml
 12K	lib
 64K	manifests
4.0K	metadata.json
4.0K	Puppetfile
184K	templates
```

So 30 megs vs 0.5 megs.

**Comment by stefanbethke** [comment]
After some debugging, I've identified librarian-puppet as the source of copying the unneeded files.

If I specify:
```
provisioner:
  name: puppet_apply
  ignored_paths_from_root:
    - .git
    - examples
    - logs
    - spec
    - test
```
librarian-puppet will only copy the needed module files over; however, librarian-puppet will have installed a complete copy of the module in the temp dir, and that will be copied over as well.

Arguably, this might better be directed at librarian-puppet, but this is a very special case. I'll try thinking about a way to properly handle both kitchen-puppet and librarian-puppet recognizing the module.

**Comment by neillturner** [comment]
closing
