### ISSUE TITLE
Make puppet_coll_remote_path useable with require_puppet_collections == false

### ISSUE THREAD

**Issue by baurmatt** [neillturner/kitchen-puppet#197]
We run our tests in a custom made Docker image which has the Puppet Collection already installed. Therefore we set `require_puppet_collections: false`. But this is a problem when it comes to the point where kitchen tries to run Puppet, as the `puppet_cmd` function defaults to `puppet` if `require_puppet_collections` is false:

https://github.com/neillturner/kitchen-puppet/blob/afbe9b806f470d71a57924fb1b59ba9289e8724e/lib/kitchen/provisioner/puppet_apply.rb#L903-L913

It would be great if the `puppet_bin` path could be set manually!

**Comment by baurmatt** [comment]
Another issue which is related. If one sets `require_puppet_collections`, `require_puppet_repo`, `require_puppet_omnibus` to false (e.g. because Puppet is already in the Docker image), it not possible to use `custom_pre_install_command` and `custom_install_command` anymore.

**Comment by neillturner** [comment]
All these are do-able. code and pretty simple. most folks just write pull requests and i review, test, merge and release them. 
it will be easy to add a parameter say puppet_cmd that you can config and get returned by the puppet_cmd call if specified.   
you need to explain your use case for using custom_pre_install_command and custom_install_command when not istallig puppet.

**Comment by neillturner** [comment]
added parameter puppet_binary
in regard to not being ale to use custom_pre_install_command and custom_install_command i recommend using the custom_pre_apply_command  to run commands before running puppet. 
released in kitchen-puppet 3.4.1
closed

**Comment by baurmatt** [comment]
Thanks! :)
