### ISSUE TITLE
puppet release package has been removed from repo

### ISSUE THREAD

**Issue by ilvidel** [neillturner/kitchen-puppet#202]
Puppetlabs have removed `puppet-release-el-6.noarch.rpm` from the `puppet5` repo, which is making kitchen render an error (see  https://tickets.puppetlabs.com/browse/CPR-621 for details and Puppetlabs' response)

Apparently, we now should be using `puppet5-release-el-6.noarch.rpm`. The same applies for the rest of EL, Fedora and SLES packages.

**Comment by jvanbrunschot-coolblue** [comment]
Hi, created a PR to a permanent fix but as a workaround you can use `puppet_yum_collections_repo: 'http://yum.puppetlabs.com/puppet5/puppet5-release-el-6.noarch.rpm'` in your provisioner config.

**Comment by ilvidel** [comment]
@jvanbrunschot-coolblue Awesome, thanks!
