### ISSUE TITLE
apt-transport-https missing

### ISSUE THREAD

**Issue by mcgege** [neillturner/kitchen-puppet#212]
Due to a [change](https://github.com/puppetlabs/puppetlabs-apt/commit/f862889455c4c9994d0afc21a84715f4bc051a9c) in `puppetlabs-apt` the provisioning of puppet5 fails on some platforms, especially (in my repo) on:
- Debian 8
- Debian 9
- Ubuntu 16.04

As a temporary workaround, I've mitigated this with `custom_pre_install_command`, see this [commit](https://github.com/dev-sec/puppet-os-hardening/pull/237/commits/f9820c32c0f78aeae51a2243fdd8c300346a8b68) ...

**Comment by neillturner** [comment]
fixed hopefully in 3.6.0
