### ISSUE TITLE
nil `basedir` when instantiating R10K::Puppetfile

### ISSUE THREAD

**Issue by mwaggett** [neillturner/kitchen-puppet#214]
A recent update to r10k started causing `TypeErrors` when using kitchen-puppet (see https://github.com/puppetlabs/r10k/issues/1188).

This is because you explicitly instantiate `R10K::Puppetfile` with a nil `basedir`: https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet/r10k.rb#L50

While this worked with previous versions of r10k, we have never intentionally/explicitly supported the use of a nil `basedir`. 
In order to fix this issue, we recommend updating the instantiation to one of the following, depending on your needs:
```
R10K::Puppetfile.new(<basedir>, { moduledir: path, puppetfile_path: puppetfile })
```
OR
```
R10K::Puppetfile.new("", { moduledir: path, puppetfile_path: puppetfile })
```
If `path` and `puppetfile` are relative paths, they will be resolved relative to the `basedir`. If they are absolute paths, `basedir` should be ignored for your particular use case.

We've deprecated some params, as seen here: https://github.com/puppetlabs/r10k/blob/ded1045f29f99a624c19eae25d96217cd0dee179/lib/r10k/puppetfile.rb#L53-L58
We'll be updating that yardoc to be clearer about how each param is used.

Apologies for the breakage! but I want to make clear that we do not consider the internals of the r10k lib to be public API, so things could potentially 'break' without a major version bump.

**Comment by neillturner** [comment]
fixed hopefully in version 3.60
