### ISSUE TITLE
git: command not found

### ISSUE THREAD

**Issue by EslamElHusseiny** [neillturner/kitchen-puppet#52]
I'm trying to use the following puppet apply provisioner parameters,
* puppet_git_init
* puppet_git_pr

with docker driver 

but in converge step I got the following error which is basically means that git isn't installed : 
>       sudo: git: command not found
> Converge failed on instance <default-centos-66>.
> Please see .kitchen/logs/default-centos-66.log for more details
> ------Exception-------
> Class: Kitchen::ActionFailed
> Message: SSH exited (1) for command: [sudo -E rm -rf /etc/puppet && sudo -E git clone https://github.com/EslamElHusseiny/puppet-java.git /etc/puppet && sudo -E git --git-dir=/etc/puppet/.git/ fetch -f origin pull/22/head:pr_22 && sudo -E git --git-dir=/etc/puppet/.git/ --work-tree=/etc/puppet/ checkout pr_22]
> ----------------------

**Comment by neillturner** [comment]
the provisioner assumes git is already installed

**Comment by EslamElHusseiny** [comment]
Great, can you please instruct me to provide a platforms pre-equiped with git, I've tried to create a docker images with git installed within but I couldn't use them in .kitchen.yml file but it returns the following error : 
> Creating <default-mycentos>...
Create failed on instance <default-mycentos>.
Please see .kitchen/logs/default-mycentos.log for more details
------Exception-------
Class: Kitchen::ActionFailed
Message: Unknown platform 'mycentos'
----------------------

and the images I have are : 
> docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
default-mycentos    latest              7dd3e54bef15        3 hours ago         300.2 MB
default-mycentos    mycentos            7dd3e54bef15        3 hours ago         300.2 MB
mycentos            latest              7dd3e54bef15        3 hours ago         300.2 MB
mycentos            mycentos            7dd3e54bef15        3 hours ago         300.2 MB
<none>              <none>              e1499aa88275        8 days ago          258.9 MB
centos              centos6             b9aeeaeb5e17        8 weeks ago         202.6 MB
centos              latest              fd44297e2ddb        8 weeks ago         215.7 MB

**Comment by ytsarev** [comment]
```
image mycentos:mycentos
platform: centos
```

**Comment by EslamElHusseiny** [comment]
Thanks a lot @ytsarev I also found another cool stuff which is provision_command http://www.rubydoc.info/gems/kitchen-docker/2.1.0#provision_command which is much easier than maintaining my custom image for each platform.

Thanks a lot
