### ISSUE TITLE
using puppet_git_init, puppet_git_pr causes errors in puppet apply step

### ISSUE THREAD

**Issue by EslamElHusseiny** [neillturner/kitchen-puppet#54]
I'm trying to use both variables : 
* puppet_git_init 
* puppet_git_pr
so as to test certain pull requests before merging, the issue is that kitchen-puppet pulls the content of git repo under /etc/puppet directly not /tmp/kitchen/modules which  kitchen-puppet uses for for puppet apply command, plus the puppet module dependencies won't be triggered.
Do I miss anything in using puppet_git_init and puppet_git_pr ?!

**Comment by ytsarev** [comment]
Right, it is a bit ambiguous at the moment, see my initial PR
https://github.com/neillturner/kitchen-puppet/pull/41
Currently I use it to deliver additional things we keep in our puppet repository(some shellmocking stuff we use for testing)
Actual replacement of puppet manifests under kitchen test with git ones is on my list.

**Comment by neillturner** [comment]
we can add a parameter install_git which defaults to false but when set to true we check if git is installed and if not install it.  the git support was contributed and i have not used it personally but happy to discuss use cases and how we can make it more robust.

**Comment by EslamElHusseiny** [comment]
@neillturner exactly the typical behavior should be as following using 
* install_git parameter to install git 
* puppet_git_init && puppet_git_pr to pull a certain pull request you wanna test against, and pull should be in /tmp/kitchen/modules/<module_name>  instead of /etc/puppet  
* get the puppet module dependencies 

so as to enable kitchen to work normally without any other hacks.

**Comment by grubernaut** [comment]
I don't feel that being able to clone pull requests into a kitchen suite to test them is within the scope of this project. Unless I'm misunderstanding the reasoning, wouldn't it be easier to use a common CI tool to test pull requests?

**Comment by EslamElHusseiny** [comment]
currently I'm using Jenkins to do the job as following : 
1- executing either librarian-puppet or r10k to pull the puppet module and its dependencies in modules directory which its path is written in .kitchen.yml conf file for modules_path parameter, unfortunately neither librarian-puppet nor r10k can pull a certain pull request, so I'm pulling the master repository.
2- using Jenkins shell build step to switch the main puppet module from master to the pull request I'm gonna test
3- launch kitchen different commands "destroy, create, converge, and verify" to start testing using puppet module and its dependencies exists in modules directory which its path is written in .kitchen.yml conf file.

**Comment by neillturner** [comment]
closing this as out of scope.
