### ISSUE TITLE
hiradata doesn't have any effect

### ISSUE THREAD

**Issue by EslamElHusseiny** [neillturner/kitchen-puppet#55]
I've the following scenario : 
in .kitchen.yaml : 
> ---
driver:
  name: docker

> provisioner:
  name: puppet_apply
  puppet_version: 3.8.1
  mainfests_path: manifests
  modules_path: modules
  hiera_config_path: hiera.yaml
  hiera_data_path: hiradata

> platforms:
  name: centos-6.6

> suites:
  name: default
    manifest: site.pp
    provisioner:
      custom_facts:
        opscenter_eni_ip: "10.0.0.254"

The opscenter_eni_ip facter can be retrieved, easily, however this fact should be passed to a hiera variable in common.yaml hiradata file, and unfortunately the hieradata variable is empty ?!

any ideas what is going wrong ?

**Comment by EslamElHusseiny** [comment]
seems like I got it,
Apparently the issue was in hiera.yaml file which points to a standard hieradata path, whereas kitchen moves the hieradata directory to /tmp/kitchen/hiera

**Comment by ytsarev** [comment]
I'm using
```                             
  hiera_data_remote_path: /etc/puppet/hieradata
```

**Comment by EslamElHusseiny** [comment]
nice hint, thanks @ytsarev
