### ISSUE TITLE
omnibus puppet script

### ISSUE THREAD

**Issue by neillturner** [neillturner/kitchen-puppet#69]
it would be good to create an omnibus puppet install shell script like we have done for kitchen_ansible.

**Comment by mmckinst** [comment]
I started doing this at https://github.com/mmckinst/puppet-bootstrap . It currently works on all the platforms puppet has an official repo for.

**Comment by neillturner** [comment]
thanks mmckinst. can i steal your install.sh for my omnibus-puppet project. i would change to default to puppet 3.x and from puppet agent to puppet apply.

**Comment by mmckinst** [comment]
Not a problem. FWIW you can install puppet 3.x with mine if you want. I just did the easy distros puppet has support for now. I might try doing more using [RVM binaries](https://rvm.io/binaries/) and installing puppet as a gem for more distros.

**Comment by neillturner** [comment]
shipped in version 1.39.0
