### ISSUE TITLE
ManifestDir is Deprecated in Puppet4

### ISSUE THREAD

**Issue by grubernaut** [neillturner/kitchen-puppet#73]
Per Puppetlabs docs, setting `--manifestdir` on puppet apply is now deprecated in puppet4. 
https://docs.puppetlabs.com/puppet/3.8/reference/deprecated_settings.html#manifestdir

This means that puppet apply fails to run when using a version of puppet > 4.x.x.

**Comment by neillturner** [comment]
there is a method 'puppet_manifestdir' that does this. how o we determine we are puppet v4????

**Comment by grubernaut** [comment]
That method depends on setting puppet_environment, or it will always include the `--manifestdir` parameter to puppet apply. 

We may be able to grab the puppet version from the test suite, but that would require yet another shell out and will slow down the entire provision process.

**Comment by nvtkaszpir** [comment]
Workaround is to use custom command to execute puppet?

**Comment by grubernaut** [comment]
Only if running puppet 4 or newer as far as I know

**Comment by josephholsten** [comment]
I just pass `puppet_environment: "hack"` to avoid passing manifestdir. but a flag to specify that puppet4 will be used would be lovely.

**Comment by neillturner** [comment]
are you setting the require_puppet_collections parameter to true to get puppet v4 installed?

**Comment by neillturner** [comment]
created pull request for this ManifestDir is Deprecated in Puppet4 #92

**Comment by neillturner** [comment]
fixed  in version 1.0.34
