### ISSUE TITLE
 Support for multiple paths for modules

### ISSUE THREAD

**Issue by nvtkaszpir** [neillturner/kitchen-puppet#77]
Feature request.

As described in Puppet documentation you can use --modulepath=path/foo:/bar/baz to select multiple directories to search for modules https://docs.puppetlabs.com/puppet/3.6/reference/dirs_modulepath.html (not to mention that windows formatting differs).

This means that config should accept Array of the directories, then it would have to trigger uploads and merge list into a line and update command to execute puppet.

Right now custom puppet command is possible, but not sure how to tell test-kitchen to upload given directories to the specific folders.

**Comment by grubernaut** [comment]
This should be fairly straightforward to accomplish.

Here we set the directory for the modules that need to be copied into the puppet sandbox. https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L571

Shouldn't be a problem to turn this into a list of modules that are copied into the sandbox modules directory.

**Comment by nvtkaszpir** [comment]
I'm sorry that I can't help, because my knowledge of the ruby is quite limited, slowly learning how it works, and the syntax is a bit different to the things I'm used to :)

**Comment by grubernaut** [comment]
Ah not a problem at all!! :) 

Was merely documenting for my own knowledge when I get back to triage this issue. Sorry for implying that you would be responsible for a fix

**Comment by nvtkaszpir** [comment]
Actually recently I feel the increasing urge to learn ruby to be able to commit more to the project, mainly because of the puppet/chef and other tools that are ruby-based. Unfortnately right now I don't have time to focus on this, but maybe around Christmas there will be some spare time :)

**Comment by grubernaut** [comment]
haha I know the feeling. I have next week off on vacation and am hoping to spend some time triaging a few of these issues in kitchen-puppet. :)

**Comment by nvtkaszpir** [comment]
Hah, don't. Go for vacation somwhere without access to the computers. I know that feeling, it's contagious! :D

**Comment by chrw** [comment]
@grubernaut Did you have the chance to have a look ? I tried to implement it myself without luck. My ruby skills are not very sophisticated. ;)

**Comment by neillturner** [comment]
ok i will try and find some time to implement.

**Comment by chrw** [comment]
Thanks Neill. Please let me know if I can help in any way. I'm curious to see the code to learn where I failed.

**Comment by neillturner** [comment]
a question if you have multiple modules directories say A B and C 
is it ok to just merge all the contents into one modules folder as that is effectively what librarian-puppet does. This assumes all the modules are unique over all the module folders. This would be a very straightforward implementation. 
otherwise i need to create a multiple multiple folders: 
 modules_A
 modules_B
 modules_C

**Comment by chrw** [comment]
For me the separation is just a kind of abstraction. I have a directory called _legacy_ to hold old and unsupported modules. The main _modules_ directory managed by r10k. And a _site_ directory with the roles and profiles "modules". So I wouldn't mind if the content is in one modules directory.

**Comment by neillturner** [comment]
This is now implemented and released in version 1.38.1. 
You can specify in modules_path parameter multiple directories
  modules_path:  'directory_a:directory_b:directory_c'
and we now just merge all the contents of the directories into one modules folder.
we assume all the modules in all the directories have different name. 

closed.
