### ISSUE TITLE
hiera package name

### ISSUE THREAD

**Issue by gomex** [neillturner/kitchen-puppet#80]
Hiera package in Debian Jessie is called just hiera and not hiera-puppet. 

I got this error:

Reading state information... Done
       E: Unable to locate package hiera-puppet

**Comment by grubernaut** [comment]
What parameters are you supplying to the provisioner? 
Also, what version of kitchen-puppet are you using? 

Thanks

**Comment by grubernaut** [comment]
The latest version of `kitchen-puppet` does not install hiera by default, but only when setting the `install_hiera` boolean. 

As shown here, http://docs.puppetlabs.com/hiera/1/installing.html; the Puppet package since Puppet 3 has included hiera in the package. Thus you should only need to install the `hiera` or `hiera-puppet` package if using puppet 2.7.x or older.

**Comment by grubernaut** [comment]
However, if you need a custom version of hiera that is different than the one supplied from the Puppet package, you'll need to install the hiera package. 

This should fix the issues you have with Jessie, https://github.com/neillturner/kitchen-puppet/pull/83

**Comment by gomex** [comment]
gomex@gondor:/tmp/puppet$ kitchen version
Test Kitchen version 1.4.2

---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  hiera_data_path: hieradata
  hiera_config_path: "hiera.yaml"
  hiera_data_remote_path: "/etc/puppet/hieradata"
  puppet_debug: true
  puppet_verbose: true

platforms:
  - name: Debian-8.1-64-bit
    driver_plugin: vagrant
    driver_config:
      box: Debian-8.1-64-bit
      box_url: https://vagrantcloud.com/debian/boxes/jessie64/versions/8.1.0/providers/virtualbox.box

suites:
  - name: padrao
    provisioner:
      manifest: site.pp

**Comment by grubernaut** [comment]
Which version of the kitchen-puppet provisioner are you using? 

Was #83 a correct solution to your problem?

**Comment by gomex** [comment]
Test Kitchen version 1.4.2

Yes! :) Thanks!
