### ISSUE TITLE
Problem with [pre|post]run etckeeper

### ISSUE THREAD

**Issue by gomex** [neillturner/kitchen-puppet#81]
I got this error:

Could not run command from prerun_command: Execution of '/etc/puppet/etckeeper-commit-pre' returned 1
Could not run command from prerun_command: Execution of '/etc/puppet/etckeeper-commit-post' returned 1

My box has these files, but something in kitchen provision remove that file. How can I fix it?

**Comment by ytsarev** [comment]
@gomex login into instance with `kitchen login` , run these commands manually and try to figure out ?

**Comment by gomex** [comment]
@ytsarev I already did that. That files was removed from box after kitchen provision :(

**Comment by neillturner** [comment]
there are a few hits on google
  https://groups.google.com/forum/#!topic/puppet-users/EtumyaMY_oM
  http://stackoverflow.com/questions/10559724/puppet-accidently-deleted-etckeeper-commit-pre-and-etckeeper-commit-post-is-ther
https://www.packtpub.com/books/content/puppet-integrating-external-tools
https://bugs.launchpad.net/openstack-cisco/+bug/1191090

kitchen-puppet just install puppet in a couple of different ways. 
it looks like you config these in the puppet.conf. is that true? 
I expect it is a puppet or ubuntu issue or something in the way you want to install puppet. 
If you can find out the issue we can alway add a parameter to kitchn-puppet to support it. 
are you running puppet apply or the puppet agent with puppetmaster. 
 there are so copies of the file: 
  https://github.com/timcowlishaw/Puppet/blob/master/etckeeper-commit-pre
I think you just need to do some research to understand what these files are.

**Comment by ytsarev** [comment]
I guess the core issue is just this /etc/puppet clean up https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L419

**Comment by ytsarev** [comment]
oh, no, scratch that, it's for git_init only

**Comment by gomex** [comment]
@neillturner I have this config in my puppet.conf:

[main]
logdir=/var/log/puppet
vardir=/var/lib/puppet
ssldir=/var/lib/puppet/ssl
rundir=/var/run/puppet
factpath=$vardir/lib/facter
prerun_command=/etc/puppet/etckeeper-commit-pre
postrun_command=/etc/puppet/etckeeper-commit-post

[master]
# These are needed when the puppetmaster is run by passenger
# and can safely be removed if webrick is used.
ssl_client_header = SSL_CLIENT_S_DN
ssl_client_verify_header = SSL_CLIENT_VERIFY

**Comment by gomex** [comment]
My workaround was: 

prerun_command=/etc/puppet/hieradata/etckeeper-commit-pre
postrun_command=/etc/puppet/hieradata/etckeeper-commit-post

hieradata folder is copied with "hiera_data_remote_path".

**Comment by gomex** [comment]
That workaround don't works in agent :( Because in the agent don't have hieradata.

Is there any other way to fix it?

**Comment by gomex** [comment]
This was fixed with #83 because now I can use jessie repository that put etckeeper files in correct place :+1: This problem will break in ubuntu packages. Is there any way to send that files to test machine?

**Comment by grubernaut** [comment]
The `spec/fixtures` directory will be copied over to the test machine if that's what you're looking for

**Comment by neillturner** [comment]
closing this as we have merged #83
