### ISSUE TITLE
 Resolution of Module Under Development from CWD

### ISSUE THREAD

**Issue by scanguskhan** [neillturner/kitchen-puppet#82]
I'm fairly new to puppet and librarian and  can't seem to align the kitchen/puppet/libraian planets.  

I gather my inexperience is leading me down an incorrect path, but is there a way for kitchen/puppet/librarian to
1. Resolve,install, and run  the current working directly as a module in my kitchen/vagrant/vitualBox VM
2. Install the module dependencies from PuppetFile into my  kitchen/vagrant/vitualBox VM
3. Have puppet invoke  a main entry manifest from my working dir that is not residing in my project roots  top level manifest directory .  I want  ./manifests directory prestine, having just init.pp class (any any other module class definitions) without having to include the puppet entry manifest in the same directory (i.e I don't want a site.pp in my modules manifest dir, or any class "declarations" for that matter...just the module class "definitions")

No matter what I try, I can't seem to get these requirements to jive. My bag of tricks is empty.  Does installation of a module under development from the CWD even supported in kitchen/puppet or do I have to package up my module and install it  via some other mechanism?   Any help, much appreciated.

**Comment by neillturner** [comment]
the way test kitchen works is it runs librarian puppet on your workstation and then merges the cookbooks downloaded with your our cookbooks and then passes them to the server in vagrant or whatever. It doesn't run librarian-puppet on the vagrant box. 

NOTE: librarian-puppet requires ruby 1.9.3 or higher while puppet on centos 6 boxes requires ruby 1.8.7 so you cannot run librarian puppet on centos 6 as well as puppet. 

If you have a windows workstation you need to download the puppet msi and install it and run everything install the puppet window. 
see http://ec2dream.blogspot.co.uk/search/label/EC2Dream%20Installation section Using EC2Dream and Puppet on Windows.  just install test-kitchen instead of ec2dream. 

1. Download and install puppet from the windows msi file from https://downloads.puppetlabs.com/windows/ (Use a 32 bit version) (NOT gem install puppet!!!).

2. Select "Start Command Prompt with Puppet" to go to a Command Window.

3. install the Ruby DevKit:
    a. Download and install devkit from http://rubyinstaller.org/downloads
         (Use a 32 bit version that matches version install inside Puppet)
    b. In the devkit directory run “ruby dk.rb init”.
    c. Edit the config.yml generated and add the the path of the ruby install for puppet
        (it will be <install dir of puppet>/sys/ruby).
    d. run “ruby dk.rb install” to bind it to the puppet ruby installation.

4. From the "Start Command Prompt with Puppet" not a normal Windows Command prompt:
    gem install librarian-puppet
    gem install test-kitchen

6. ALWAYS run test-kitchen from the "Start Command Prompt with Puppet" not a normal Windows Command prompt.

 i have a sample puppet repo you can use at https://github.com/neillturner/puppet_repo

I put my modules in a directory modules_mycompany when mycompany is a company identify ie if you were microsoft you might have a directory modules_ms 

then in the .kitchen.yml file you have: 
  name: puppet_apply
  manifests_path:  manifests
  modules_path: modules_ms
  hiera_data_path: hieradata 

you should run 
   librarian-puppet install --verbose
in a command line in the directory of your puppetfile to debug it. 

Hope that's helpful. Just let me know if you need more help.

**Comment by scanguskhan** [comment]
Very helpful, Thanks for the info.  I reinstalled following the instructions, with the exception that I installed all 64bit distributions for my 64bit laptop (You called for 32 but distros, so let me know if that's somehow gonna be a problem)

In any event, I'm apparently now  still missing the puppet_apply provisioner. Where does that come from?

kitchen converge
>>>>>> Message: Could not load the 'puppet_apply' provisioner from the load path
. Please ensure that your provisioner is installed as a gem or included in your
Gemfile if using Bundler.

**Comment by neillturner** [comment]
yes you need to also 
 gem install kitchen-puppet
let me know how you get on. I found problems with 64 bit versions but think change rapidly in the ruby world. -)

**Comment by scanguskhan** [comment]
OK. So, I'm all installed and back to my original problem, which I think I probably did  a lousy job explaining. I'll try again.(hopefully better, but no promises :) ) 

 If I am developing a puppet module, then my manifest directory in my project directory contains only my "module" manifests (i.e init.pp and supported class manifests).  It  contains only class "definitions" (i.e init.pp) and not any class "declarations" (i.e site.pp) .   Class declarations normally reside in some other main entry manifest (i.e site.pp) outside any modules manifest directory.  In other words, noone ships a site.pp in their module, so it doesn;t belong in a modules manifest directory. Normally,  you ship only class definitions, then other people declare your classes in their site.pp.  

In all the example of kitchen and/or vagrant/puppet, the top-level manifest directory contains a main entry manifest (i.e site.pp) which declares instances of classes.  This seems to conflict with module development directory standards where the top-level manifest directory is for "module" manifests which ultimately get shipped as part of your module, and which do not contain module declarations (like a site.pp) 
 

So the use case I'm hoping to  get to work is.

As a module developer, I want to 
1. Utilize the standard module directory structure where the top-level manifest directory is for shippable "module" manifests ONLY.
2.  Have kitchen install my module under developemnet (effectively the current working dir) and run some main entry manifest  that doesn not  reside in my module project's manifest directory.

So how does one test a module under development, given that it is the CWD that is the module you want to test, and given  that the top level manifest directory of a module normally  does not contain a main entry  manifest?  In other swords, If I  put a .kitchen.yaml file in my module standard directory structure for the purpose of testing that module, and invoke kicthen, kitchen doesn't  install the module under development (i.e the CWD), nor do I  even have any class declarions in my manifest dir to serve as the main entry point for the puppet run.

**Comment by neillturner** [comment]
Well i use a puppet forge module called role that i wrote. 
   https://forge.puppetlabs.com/neillturner/role
each role is a module in module-ms folder (continuing my microsoft analogy)
so i have a ms_base module for the base role. 
this roles are functionally based. they called via librarian-puppet all the roles 
like nodejs, apache etc etc that do the real work of configuring the server. 
 But this is just how i do it. Other people use the r10k module. you need to figure out how you wish to do this. Puppet is not like chef where you can define roles. You have to create your own framework that is what my role module and the r10k module does.

**Comment by neillturner** [comment]
puppet is a repository centred system rather than module centred. chef is more cookbook centred particularly f you use berkshelf,

**Comment by grubernaut** [comment]
iirc the `copy-self-as-module` parameter should do the trick for you.

**Comment by neillturner** [comment]
I'm not that up on this part of puppet -) 
as per https://github.com/neillturner/kitchen-puppet/pull/11
does this mean it will pickup the module name from the metadata.json file 
and you can specify the modulefile_path and the metadata_json_path

**Comment by scanguskhan** [comment]
copy-self-as-module parameter sounds very promising, though I'm not able to find any info on it.  What is it a parameter to?  Anybody have a pointer to info on it?

**Comment by grubernaut** [comment]
Sorry, I misspoke, it's not a parameter, but a method called from the `prepare_modules` method. 

https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L874-L911

The `copy_self_as_module` method, should read info in about your module if `metadata.json` is found by the provisioner. https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L118-L120

If `metadata.json` is not found by the provisioner, you can always manually specify it with the `metadata_json_path` parameter.

**Comment by scanguskhan** [comment]
I hand crafted my module directory and did not have a metadata.json which explains which copy_self_as_module wasn't copying my module to the vagrant box.     I have since added a metadata.json and now see that my module under development is being copied to my vagrant box into /tmp/kitchen/modules.

However, if I have also have  "include foo" , where foo is my module under developememt (i.e the "self" in copy-self-as-module)  in my main entry point manifest (i.e in site.pp),  the puppet run always complains that it can not find my module.

So while  the copy of the module seems to work fine so long as you have a metadata.json file, puppet is still unable to resolve the main class of that module (at least for me) 

c:\git\foo>kitchen converge
-----> Starting Kitchen (v1.4.2)
-----> Converging <default-ubuntu-1204>...
       Preparing files for transfer
       Preparing modules
       Resolving module dependencies with Librarian-Puppet 2.2.1...
       nothing to do for modules
       Preparing manifests
       Preparing files
       Finished Preparing files for transfer
       Installing puppet on ubuntu-12.04
       Transferring files to <default-ubuntu-1204>
       Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
          (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
       Error: Could not find class foo for default-ubuntu-1204 on node default-ubuntu-1204
       Error: Could not find class foo for default-ubuntu-1204 on node default-ubuntu-1204
>>>>>> Converge failed on instance <default-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [   sudo -E puppet apply /tmp/kitchen/manifests/default.pp --modulepa
th=/tmp/kitchen/modules --manifestdir=/tmp/kitchen/manifests --fileserverconfig=/tmp/kitchen/fileserver.conf
  ]
>>>>>> ----------------------
zlib(finalizer): the stream was freed prematurely.

**Comment by chrisN777** [comment]
Yesterday, I had a hard time too, getting my module and all dependencies right for kitchen-puppet.
You should definetly take a look at copy_self_as_module https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L895-L915 which uses the module name defined in metadata.json and splits it at the last '-'. Maybe take a look into your VM with
```
   kitchen login default-ubuntu-1204
   ls /tmp/kitchen/modules
```
and check if your module foo is their and contains an init.pp with a class named foo.

I 've got the setup working now if you wan't to take a look: https://github.com/chrisN777/puppet-docker-hardening.

This part definitly needs a bit more documentation. The PR is on my todo list.

**Comment by chrisN777** [comment]
PR with a doc hint is here: https://github.com/neillturner/kitchen-puppet/pull/89

**Comment by neillturner** [comment]
merged hint so closing
