### ISSUE TITLE
`puppetfile_path` does not correctly install Puppet Modules

### ISSUE THREAD

**Issue by xaniasd** [neillturner/kitchen-puppet#85]
Hi there,

As an example, I'm using the following Puppetfile:
```
forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs/stdlib'
mod 'elasticsearch/logstash',
  :git => 'git@github.com:elastic/puppet-logstash.git',
  :ref => '0.5.1'
```
to define a dependency to my module. My .kitchen.yml:
```yaml
---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: test/integration
  puppetfile_path: spec/fixtures/Puppetfile
  manifest: default/init.pp
  modules_path: modules
  require_chef_for_busser: false
```
This setup is giving me the following error:
```
       Resolving module dependencies with Librarian-Puppet 2.2.1...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [Could not checkout git@github.com:elastic/puppet-logstash.git: fatal: Not a git repository: 'spec/fixtures/.tmp/librarian/cache/source/git/a546444c477b9bef/.git'
]
>>>>>> ----------------------
```
I tried with https as well, with the same results.
Here's the backtrace:
```
ERROR -- Kitchen: ------Backtrace-------
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/git.rb:37:in `rescue in cache!'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/git.rb:34:in `cache!'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarianp-0.6.3/lib/librarian/source/local.rb:22:in `manifest_search_paths'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarianp-0.6.3/lib/librarian/source/local.rb:31:in `found_path'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/local.rb:15:in `install!'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarianp-0.6.3/lib/librarian/manifest.rb:73:in `install!'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarianp-0.6.3/lib/librarian/action/install.rb:49:in `block in install_manifests'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarianp-0.6.3/lib/librarian/action/install.rb:48:in `each'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarianp-0.6.3/lib/librarian/action/install.rb:48:in `install_manifests'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarianp-0.6.3/lib/librarian/action/install.rb:39:in `perform_installation'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/librarianp-0.6.3/lib/librarian/action/install.rb:12:in `run'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/kitchen-puppet-1.0.32/lib/kitchen/provisioner/puppet/librarian.rb:50:in `resolve'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/kitchen-puppet-1.0.32/lib/kitchen/provisioner/puppet_apply.rb:968:in `block in resolve_with_librarian'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/kitchen-puppet-1.0.32/lib/kitchen/provisioner/puppet_apply.rb:966:in `synchronize'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/kitchen-puppet-1.0.32/lib/kitchen/provisioner/puppet_apply.rb:966:in `resolve_with_librarian'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/kitchen-puppet-1.0.32/lib/kitchen/provisioner/puppet_apply.rb:880:in `prepare_modules'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/kitchen-puppet-1.0.32/lib/kitchen/provisioner/puppet_apply.rb:398:in `create_sandbox'
ERROR -- Kitchen: ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:61:in `call'
```
If I explicitly install with librarian-puppet at spec/fixtures, it's working just fine. 

So am I doing something wrong, or is it a bug?

cheers

**Comment by grubernaut** [comment]
Can you also try adding the `resolve_with_librarian_puppet` provisioner parameter to `true`? 

Can you resolve that module with librarian, outside of test-kitchen? 

`librarian-puppet install`?

**Comment by xaniasd** [comment]
The default value is true, I set it explicitly as well with the same results.
And yes, ```librarian-puppet install``` works fine.

**Comment by grubernaut** [comment]
This is working for me with librarian version 2.0.1, let me test with 2.2.1, as you are using.

**Comment by grubernaut** [comment]
This is also working for me with version 2.2.1 of librarian. 

Do you require your Puppetfile to live outside of your project's root?

**Comment by xaniasd** [comment]
Hmm, then I'm doing something wrong..
No, the Puppetfile is under <module_root>/spec/fixtures

**Comment by grubernaut** [comment]
By convention, the Puppetfile is usually located at the root of the project. 

If possible, would you be able to try copying the `Puppetfile` from `/spec/fixtures` to the root of your project, and removing the `puppetfile_path` parameter? I have a feeling it might be the `puppetfile_path` parameter that has a bug, as all of my tests were with the `Puppetfile` in the root of the project

**Comment by xaniasd** [comment]
yep, that did the trick. Thanks a lot! And, we found a bug :)

**Comment by grubernaut** [comment]
Awesome! Cool, I'll label this as such, and someone will get to it shortly.

**Comment by neillturner** [comment]
I don't think this is a bug as the puppetfile has to be in the root of the project.
 
see:  https://github.com/voxpupuli/librarian-puppet

Every Puppet repository that uses Librarian-puppet may have a file named Puppetfile, metadata.json or Modulefile in the root directory of that repository. The full specification for which modules your puppet infrastructure repository depends goes in here.

not quite sure why we have puppetfile_path. We could copy the puppetfile from the path to the root of the puppet repo but this would change the repo of the user's workstation. 

closing.

**Comment by madAndroid** [comment]
We're experiencing this issue as well; our use case is slightly different, so it does differ from the standard approach of keeping only a single `Puppetfile` in the root of the repo: we manage two Puppetfiles, one is the "standard" one in the root of the repo, and a `Puppetfile` used explicitly for testing. This `Puppetfile` defines test dependencies, which are not necessarily required by the module itself, and are only used during testing in rspec, and originally Beaker as well (we're moving from Beaker to Test-Kitchen).

I'll see if we can implement some logic in our rake tasks to handle this slightly different use case, which will copy the `Puppetfile` referenced in `puppetfile_path` to the root of the repo, but it would be great if we didn't have to explicitly do that.
