### ISSUE TITLE
Request for enhancement: add custom puppet config settings

### ISSUE THREAD

**Issue by looztra** [neillturner/kitchen-puppet#87]
In one of my usecase I need to specify the option *stringify_facts* to the puppet apply command line.

There are 2 ways to do that for the moment:
* provide a custom puppet.conf file
* use *puppet_apply_command*

I personnaly find these 2 solutions too *heavy* for what I need to do (especially the override of *puppet_apply_command* because I need to rebuild the full command line, see https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L521-L539).

My proposal would be to provide an extra param that would allow the user to specify the extra args to the command line.

Could be something like `puppet_extra_conf_settings`, and in my case I would value it to `--no-stringify_facts`.

what do you think about it?

If that seems ok for you I can submit a PR.

**Comment by neillturner** [comment]
in my kitchen_ansible i have variable 
 ansible_extra_flags
when you can put in extra flags for the command like 
'--skip-tags=redis'

apparently in puppet any setting that's valid in the configuration file can be specified on the command line so i suggest implement something similar.
we can have a parameter  puppet_extra_flags that you can set to 
 '--no-stringify_facts'
we can get the code from kitchen-ansible its just a few lines. 
Once again it you want to implement do a pull and change and push us the change and we will review. 
Once again Any comments from my collaborators @grubernaut @ytsarev .

**Comment by neillturner** [comment]
I think instead of puppet_extra_flags
we could call the parameter just options

**Comment by looztra** [comment]
Yep, I can totally craft a PR for that :). `options` is good for me.

Do we need to support that for the `puppet_agent` provisionner too?

**Comment by neillturner** [comment]
not unless you need it. the puppet_agent is a fair way behind the puppet_apply. One day we should get all the puppet_apply features into puppet_agent but I suspect most people are using puppet_apply

**Comment by ytsarev** [comment]
@looztra  For me something simple as `custom_options` which will amend standard tool constructed invocation is good enough to solve this problem, so please go shoot the PR, we will appreciate :)

**Comment by looztra** [comment]
I will work on it these days and should be able to provide a PR soon

**Comment by neillturner** [comment]
this is now PR Custom options #95

**Comment by neillturner** [comment]
fixed in version 1.0.34
