### ISSUE TITLE
Unsupported Platform Error with Cumulus VX

### ISSUE THREAD

**Issue by rmaika** [neillturner/kitchen-puppet#91]
I have a development environment configured with test-kitchen, vagrant, and puppet. One of the scenarios I'm using this environment for is deploying 5 instances of Cumulus VX (virtualized switch OS), and provisioning them with Puppet. 

I am on version 0.0.24 since I set my environment up a while back, and when a co-worker tried to set up his environment he installed the latest (version 1.0.33) and got an error from the gem that said Cumulus VX is not a platform that Puppet can be installed on. The error was resolved by uninstalling that version and manually selecting version 0.0.24 to match the version that it's working on my machine using.

Any idea where the breaking change for Cumulus VX platform might be, and any chance that this behaviour could be restored for the Cumulus VX platform in the more recent versions?

Thanks,
Raymond

**Comment by neillturner** [comment]
if you run with -l debug and look at the log then we can see why the install is failing. The install options have been expanded since 0.0.24. So it depends how you are installing puppet.

**Comment by ytsarev** [comment]
@rmaika this issue should also be fixed by https://github.com/neillturner/kitchen-puppet/pull/99

**Comment by rmaika** [comment]
@ytsarev I would agree, thanks!

@neillturner any chance we could get a new version of the gem cut with patch #99  included?

**Comment by neillturner** [comment]
fixed in 1.0.35
