### ISSUE TITLE
platform name regression

### ISSUE THREAD

**Issue by ytsarev** [neillturner/kitchen-puppet#94]
https://github.com/neillturner/kitchen-puppet/pull/68 brought regression

in form of platform config collision

If I have in my .kitchen.yml platform entry like
```
  platforms:
  - name: fake
 ```
then converge will fail with
 ```
    >>>>>> Unsupported Platform - fake
    >>>>>> Unsupported Platform - fake
    >>>>>> ------Exception-------
    >>>>>> Class: Kitchen::ActionFailed
    >>>>>> Message: Failed to complete #converge action: [undefined method
    >>>>>> `split' for true:TrueClass]
```

**Comment by neillturner** [comment]
@grubernaut  are comments on this?

**Comment by ytsarev** [comment]
@grubernaut can you please clarify expected behavior brought by #68 ? it seems that kitchen notion of `platform` should include a number of expected linux distribution names ?
If yes, then it is wrong and limiting assumption.

**Comment by grubernaut** [comment]
Yeah, it is based on assumptions and isn't correct. Sorry for this :( 

The goal was to have the apt/yum repo setup correctly based on the platform. `ubuntu-12.04`, `ubuntu-14.04`, and so on. Using the traditional platform naming style that most default vm's have.

We made the variable `platform` be configurable at the provisioner level, so you could configure the platform if your existing platform had a weird name, such as `fake` above. I'm guessing that doesn't solve your issue though?

**Comment by ytsarev** [comment]
not really as in my case platforms have semantic of custom puppet types/roles and have no distro flavor reflected there

**Comment by grubernaut** [comment]
Yeah I could see where this would break things if using multiple platforms, as you can't define a set platform for a suite, if you're using multiple platforms. 

Ah well, was hoping it would fix some repo issues automatically
