### ISSUE TITLE
Unsupported Platform - windows 

### ISSUE THREAD

**Issue by lucky27** [neillturner/kitchen-puppet#98]
Hi,

I am trying to use test-kitchen to test windows modules, but getting different errors. Could you please guide me how to fix this, I am new to using test-kitchen.
When I ran `kitchen converge` looks like its trying to install puppet, is there a way to skip that? Since our vagrant boxes are already shipped with puppet. Also would it possible to install puppet on windows using kitchen commands ? 

This is my .kitchen.yml file..
---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  puppet_debug: true
  puppet_verbose: true

platforms:
  - name: windows-2012R2
    driver:
      username: _puppet
      password: vagrant
      guest: windows
      box: win2012r2-virtualbox
    transport:
      name: ssh

suites:
  - name: default
    provisioner:
     manifest: site.pp

I tried kitchen converge first fails with 
*STDERR: Vagrant is configured to generate a random keypair and insert it
onto the guest machine, but it appears Vagrant doesn't know how to do
this with your guest OS. Please disable key insertion by setting
`config.ssh.insert_key = false` in the Vagrantfile.*

I tried to run it again..this time It asks me to enter password, after entering it fails with unsupported platform error. I am using test-kitchen 1.4.2 version, kitchen-puppet 1.0.34 version, kitchen-vagrant 0.19.0.

Below are the detailed errors,

First 

https://gist.github.com/lucky27/8a819668fc6e835700b6

https://gist.github.com/lucky27/4188275ac66679466878

**Comment by ytsarev** [comment]
Looks like `unsupported platform` part directly relates to #94 .
@grubernaut  let's decide how to proceed here

**Comment by ytsarev** [comment]
@grubernaut my proposal https://github.com/neillturner/kitchen-puppet/pull/99

**Comment by ytsarev** [comment]
I've also created https://github.com/neillturner/kitchen-puppet/issues/100 to address enhancement side separately

**Comment by ytsarev** [comment]
@lucky27 feel free to try out https://github.com/neillturner/kitchen-puppet/pull/99 , it should fix your issue with unsupported platform failure

**Comment by neillturner** [comment]
Currently we don't have windows support but it should not be difficult to add. 
Unfortunately my laptop is not powerful enough to run the full windows 2012r2 virtual box.
i can run windows nano but you have to use remote powershell to install openssh etc as the winrm support doesn't work. 
i'll look to see if i can run some other windows version under virtual box.

**Comment by lucky27** [comment]
@ytsarev I tried using #99, unsupported error is gone but it is throwing a different error now.

https://gist.github.com/lucky27/27141a1affadcf85d93d

@neillturner We use lot of windows modules, so adding windows support would be lot helpful for us.
Please let me know If u need any help with testing code on windows platforms.

Also I have another question, right now our folder structure is we have manifest folder(with contents of module I want to test) and modules folder with dependencies. I would like to add a site.pp file to all our modules, which has some custom settings like our inhouse chocolatey-nuget repository and other settings. Where should I add this? and how should I use it in the .kitchen.yml file?

**Comment by neillturner** [comment]
a couple of questions: 
1. how do you install puppet on your windows servers. msi, choclately or ruby and puppet individually? 
2. when you access your server via ssh is puppet in the path and available to execute. 

I was thinking of creating a minimal windows version that assumes that puppet is install and available on the path. 

 kitchen puppet has 2 parameters:
 manifest which defaults to 'site.pp' which is the initial manifest that is run. 
 manifests_path:  which defaults to the top level folder.

you can see an example in https://github.com/neillturner/puppet_repo
where there is a manifests folder  containing site.pp 
and the .kitchen.yml file has parameter 
  manifests_path:  manifests

**Comment by lucky27** [comment]
@neillturner I use chocolatey to install it and yes puppet is available on path.

Below is the puppet module structure I want to add, **development** folder has **site.pp** which has global settings and **manifests/init.pp** file contains the current module..how should I add these 2 in **.kitchen.yml** ? **modules** folder has the dependency modules.
![image](https://cloud.githubusercontent.com/assets/14243136/11346373/581bc3c4-91ea-11e5-9169-c69829332095.png)

**Comment by neillturner** [comment]
closing this in favour of Windows Support #79
